server:
  port: 8080


spring:
  profiles:
    group:
      "local": "local_db"
      "dev": "dev_db"
  servlet:
    multipart:
      max-file-size: 3MB

---
# local setting
spring:
  config:
    activate:
      on-profile: "local_db"
    import:
      - application-aws.yml
      - application-email.yml
  datasource:
    url: jdbc:h2:tcp://localhost/~/studit
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: never

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

app:
  backhost : http://localhost:8080
  fronthost : http://localhost:3000
  imageDir : static

---


spring:
  config:
    activate:
      on-profile: "dev_db"
  datasource:
    url: jdbc:mysql://${rds.hostname}:${rds.port}/${rds.db.name}
    username: ${rds.username}
    password: ${rds.password}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
#      ddl-auto: create-drop
    properties:
      hibernate:
        default_batch_fetch_size: 100
    defer-datasource-initialization: true
  sql:
    init:
      mode: never


app:
  backhost : studit-back.ap-northeast-2.elasticbeanstalk.com


