spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: jinunudev@gmail.com
    password: qxlifegwzgzeycjg
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true