spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/studit
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
mybatis:
  type-aliases-package: kr.co.studit.dto.mapper
  mapper-locations: mapper/**/*.xml
logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace

---

spring:
  config:
    import: application-email.yml



