drop table if exists bookmark CASCADE ;
drop table if exists member CASCADE ;
drop table if exists member_invitation CASCADE ;
drop table if exists member_position CASCADE ;
drop table if exists member_region CASCADE ;
drop table if exists member_skill CASCADE ;
drop table if exists portfolio CASCADE ;
drop table if exists positions CASCADE ;
drop table if exists position_type CASCADE ;
drop table if exists region CASCADE ;
drop table if exists skill CASCADE ;
drop table if exists study CASCADE ;
drop table if exists study_application CASCADE ;
drop table if exists study_participation CASCADE ;
drop table if exists study_position CASCADE ;
drop table if exists study_skill CASCADE ;
drop table if exists study_tool CASCADE ;
drop table if exists study_zone CASCADE ;
drop table if exists tool CASCADE ;
drop sequence if exists hibernate_sequence;

create sequence hibernate_sequence start with 1 increment by 1;

create table bookmark (
                          bookmark_id bigint not null,
                          created_date timestamp,
                          mark_member_id bigint,
                          marked_member_member_id bigint,
                          marked_study_study_id bigint,
                          primary key (bookmark_id)
);

create table member (
                        member_id bigint generated by default as identity,
                        created_date timestamp,
                        modified_date timestamp,
                        bio varchar(255),
                        emai_check_token varchar(255),
                        email varchar(255),
                        email_check_token_generated_at timestamp,
                        email_verified boolean not null,
                        nickname varchar(255),
                        on_off_status varchar(255),
                        password varchar(255),
                        password_find_token varchar(255),
                        password_find_token_generated_at timestamp,
                        profile_img varchar(255),
                        public_profile boolean,
                        role varchar(255),
                        study_type varchar(255),
                        primary key (member_id)
);

create table member_invitation (
                                   member_invitation_id bigint not null,
                                   created_date timestamp,
                                   modified_date timestamp,
                                   message varchar(255),
                                   member_id bigint,
                                   position_id bigint,
                                   study_id bigint,
                                   primary key (member_invitation_id)
);

create table member_position (
                                 id bigint generated by default as identity,
                                 member_id bigint,
                                 position_id bigint,
                                 primary key (id)
);

create table member_region (
                               member_region_id bigint not null,
                               member_id bigint,
                               region_id bigint,
                               primary key (member_region_id)
);

create table member_skill (
                              id bigint generated by default as identity,
                              member_id bigint,
                              skill_id bigint,
                              primary key (id)
);

create table portfolio (
                           portfolio_id bigint not null,
                           url varchar(255),
                           member_id bigint,
                           primary key (portfolio_id)
);

create table positions (
                           position_id bigint not null,
                           position_name varchar(255),
                           position_type_id bigint,
                           primary key (position_id)
);

create table position_type (
                               position_type_id bigint not null,
                               position_type_name varchar(255),
                               primary key (position_type_id)
);

create table region (
                        region_id bigint generated by default as identity,
                        area varchar(255),
                        primary key (region_id)
);

create table skill (
                       skill_id bigint generated by default as identity,
                       skill_name varchar(255),
                       position_id bigint,
                       primary key (skill_id)
);

create table study (
                       study_id bigint not null,
                       created_date timestamp,
                       modified_date timestamp,
                       content varchar(255),
                       duration varchar(255),
                       on_off_status varchar(255),
                       reception_end varchar(255),
                       reception_start varchar(255),
                       study_day varchar(255),
                       title varchar(255),
                       type varchar(255),
                       member_id bigint,
                       region_region_id bigint,
                       primary key (study_id)
);

create table study_application (
                                   study_application_id bigint not null,
                                   created_date timestamp,
                                   modified_date timestamp,
                                   message varchar(255),
                                   member_id bigint,
                                   position_id bigint,
                                   study_id bigint,
                                   primary key (study_application_id)
);

create table study_participation (
                                     study_participation_id bigint not null,
                                     member_id bigint,
                                     position_id bigint,
                                     study_id bigint,
                                     primary key (study_participation_id)
);

create table study_position (
                                study_position_id bigint not null,
                                count integer,
                                total_count integer,
                                position_id bigint,
                                study_id bigint,
                                primary key (study_position_id)
);

create table study_skill (
                             study_skill_id bigint not null,
                             skill_id bigint,
                             study_id bigint,
                             primary key (study_skill_id)
);

create table study_tool (
                            study_tool_id bigint not null,
                            study_id bigint,
                            tool_id bigint,
                            primary key (study_tool_id)
);

create table study_zone (
                            study_zone_id bigint not null,
                            study_id bigint,
                            zone_id bigint,
                            primary key (study_zone_id)
);

create table tool (
                      tool_id bigint generated by default as identity,
                      tool_name varchar(255),
                      primary key (tool_id)
);

alter table member
    add constraint UKfkaovnen2l4coihx0ggycgfmt unique (email, nickname);

alter table region
    add constraint UK12sjndkkrwgapyemvlve2ye5y unique (area);


alter table bookmark
    add constraint FK42ibh03q861txdqml166dgfr9
        foreign key (mark_member_id)
            references member;

alter table bookmark
    add constraint FKik0erj8tywmxg948xaysc8bsx
        foreign key (marked_member_member_id)
            references member;

alter table bookmark
    add constraint FK3hkp7ihmfv4bgm2u55uma5itw
        foreign key (marked_study_study_id)
            references study;

alter table member_invitation
    add constraint FKp2jiqs2tpwcaev62vqvwiruni
        foreign key (member_id)
            references member;

alter table member_invitation
    add constraint FKo9nw46eq0rlv6kvb69wqkhgx7
        foreign key (position_id)
            references positions;

alter table member_invitation
    add constraint FKinccbh39ihsi5pefhogjjrnlj
        foreign key (study_id)
            references study;

alter table member_position
    add constraint FKcw4p2n48d7acr5sgnh36ygip9
        foreign key (member_id)
            references member;

alter table member_position
    add constraint FKmflfmb6atvyjo85afikxhp89q
        foreign key (position_id)
            references positions;

alter table member_region
    add constraint FKidxtr6gj34jomux2hl6ndhh4o
        foreign key (member_id)
            references member;

alter table member_region
    add constraint FKni5rb06cm3rmodcu98o9wvbmx
        foreign key (region_id)
            references region;

alter table member_skill
    add constraint FKam4vlts2ujppc0xfd8y1mn4kt
        foreign key (member_id)
            references member;

alter table member_skill
    add constraint FK2jli5xtaeilnfr433cmgmi3y1
        foreign key (skill_id)
            references skill;

alter table portfolio
    add constraint FKhkjiiwx38ctlby4yt4y82tua7
       foreign key (member_id)
       references member;

alter table positions
    add constraint FKq0cuex4uffsynhn92umc3snie
        foreign key (position_type_id)
            references position_type;

alter table skill
    add constraint FKqg5kkmeburl8uw0gmu5ojowm0
        foreign key (position_id)
            references positions;

alter table study
    add constraint FKf561xlrfo0qtpl3vwkxiw4cs8
        foreign key (member_id)
            references member;

alter table study
    add constraint FKrjomkv27iso48enswfffn7yvm
        foreign key (region_region_id)
            references region;

alter table study_application
    add constraint FKa5thlrdutadb6ua74q4w755e4
        foreign key (member_id)
            references member;

alter table study_application
    add constraint FKefocm557k0haotcf6qwmoots1
        foreign key (position_id)
            references positions;

alter table study_application
    add constraint FKjl6a87co92a606r5hbwmg4m6m
        foreign key (study_id)
            references study;

alter table study_participation
    add constraint FKjulhhxywxmn9mpu0yqd4j2cut
        foreign key (member_id)
            references member;

alter table study_participation
    add constraint FK204vpl4ws8ooivucsrnyxs3p8
        foreign key (position_id)
            references positions;

alter table study_participation
    add constraint FKqinpu53w6it21e58sh7k84942
        foreign key (study_id)
            references study;

alter table study_position
    add constraint FKpdkwvou0hmv8n032t3x87xdfn
        foreign key (position_id)
            references positions;

alter table study_position
    add constraint FKbien9mn2or81b3qm17ohrl1k6
        foreign key (study_id)
            references study;

alter table study_skill
    add constraint FKnhcjrfh3y72tjg4pf6khs637x
        foreign key (skill_id)
            references skill;

alter table study_skill
    add constraint FKfdro9ek8kngd4mvx92vwkgx1j
        foreign key (study_id)
            references study;

alter table study_tool
    add constraint FK5r1hmygxa3vtsq7b2ikalybvv
        foreign key (study_id)
            references study;

alter table study_tool
    add constraint FK5xry3ftqi3kap7tukwpp23m9b
        foreign key (tool_id)
            references tool;

alter table study_zone
    add constraint FK6mqr50bw4ttigfe57mvimen63
        foreign key (study_id)
            references study;

alter table study_zone
    add constraint FKf7uwlryx5dqrbqiln4383clyk
        foreign key (zone_id)
            references tool;